source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'haml-rails'
gem 'zurb-foundation'
gem 'rspec-rails'
gem 'omniauth'
gem 'figaro'
gem 'rails_12factor', group: :production
gem 'backbone-on-rails'

group :doc do
  gem 'sdoc', require: false
end
